name = "Scapin"
uuid = "188fbd9f-a8f7-4e5f-b596-5bdd7575274e"
authors = ["Sébastien Brisard <sbrisard@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
